remote_theme: WildCodeSchool/workshops-jekyll-theme

# disable the jekyll-titles-from-headings plugin, 
# so first h1 will not be used as prior title of you page
titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "tic-tac" # possible values: default or tic-tac

style: dev # possible values: dev, data, ciber, design or wild.
title: 'API Client / Serveur'
description: 'Exposer et consommer une API dans un projet PHP MVC'
# type: ''
main_image: 'biznutz.png' # http or relative path to image
show_clone: true
show_toc: false
lang: fr